[package]
name = "nitro-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
raiko-lib = { workspace = true }
aws-nitro-enclaves-nsm-api = { workspace = true }
serde_bytes = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
vsock = { workspace = true }
libc = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true    }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
byteorder = { workspace = true }
