[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bar"
path = "src/bar.rs"

[[bin]]
name = "foo"
path = "src/foo.rs"

[dependencies]
sp1-zkvm ={ git = "https://github.com/succinctlabs/sp1.git", branch = "main"}
harness = { path = "../../harness" }


[workspace]