[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bar"
path = "src/bar.rs"

[[bin]]
name = "foo"
path = "src/foo.rs"


[dependencies]
sp1-zkvm ={ git = "https://github.com/succinctlabs/sp1.git", branch = "main"}
harness = { path = "../../harness" }

alloy-primitives = { version = "0.7.0", default-features = false }
c-kzg-taiko = { git = "https://github.com/smtmfft/c-kzg-4844", branch = "for-alpha7", default-features = false, features = [
    "preload-kzg-settings",
] }
sha2 = "0.10.8"

[workspace]