[workspace]

[package]
name = "brevis-pico-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "brevis-batch"
path = "src/bin/brevis_batch.rs"

[[bin]]
name = "brevis-aggregation"
path = "src/bin/brevis_aggregation.rs"

[[bin]]
name = "brevis-shasta-aggregation"
path = "src/bin/brevis_shasta_aggregation.rs"

[dependencies]
raiko-lib = { path = "../../../lib" }
pico-sdk = { git = "https://github.com/brevis-network/pico", package = "pico-sdk", default-features = false, features = ["kb"] }
sha2 = "0.10"

[patch.crates-io]
revm = { git = "https://github.com/taikoxyz/revm.git", branch = "v36-taiko-shasta" }
revm-primitives = { git = "https://github.com/taikoxyz/revm.git", branch = "v36-taiko-shasta" }
revm-precompile = { git = "https://github.com/taikoxyz/revm.git", branch = "v36-taiko-shasta" }
blst = { git = "https://github.com/smtmfft/blst.git", branch = "v0.3.15-serialize" }
c-kzg = { git = "https://github.com/brechtpd/c-kzg-4844", branch = "for-alpha7" }
