[workspace]

[package]
name = "risc0-guest"
version = "0.1.0"
edition = "2021"

[lib]
name = "zk_op"
path = "src/zk_op.rs"

[[bin]]
name = "sha256"
path = "src/benchmark/sha256.rs"

[[bin]]
name = "ecdsa"
path = "src/benchmark/ecdsa.rs"

[dependencies]
raiko-lib = { path = "../../../lib", features = ["std", "risc0"] }
risc0-zkvm = { version = "0.21.0", default-features = false, features = [
    'std',
    "getrandom",
] }
revm-precompile = { git = "https://github.com/taikoxyz/revm.git", branch = "v36-taiko", default-features = false, features = [
    "std",
    "c-kzg",
    "taiko",
]}

k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.0" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risczero.0" }
harness-core = { path = "../../../harness/core" }
harness = { path = "../../../harness/macro", features = ["risc0"] }

[patch.crates-io]
# Can't use ZkOp since it's big int optimization used everywhere
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risczero.0" }
revm = { git = "https://github.com/taikoxyz/revm.git", branch = "v36-taiko" }
revm-primitives = { git = "https://github.com/taikoxyz/revm.git", branch = "v36-taiko" }
c-kzg = { git = "https://github.com/brechtpd/c-kzg-4844", branch = "for-alpha7" }
secp256k1 = { git = "https://github.com/CeciliaZ030/rust-secp256k1", branch = "sp1-patch" }