[workspace]

[package]
name = "risc0-guest"
version = "0.1.0"
edition = "2021"

[lib]
name = "zk_op"
path = "src/zk_op.rs"

[[bin]]
name = "sha256"
path = "src/benchmark/sha256.rs"

[[bin]]
name = "ecdsa"
path = "src/benchmark/ecdsa.rs"

[dependencies]
raiko-primitives = { path = "../../../primitives" }
raiko-lib = { path = "../../../lib", features = ["std", "risc0"] }
risc0-zkvm = { version = "0.21.0", default-features = false, features = ['std', "getrandom"] }
revm-precompile = { git = "https://github.com/taikoxyz/revm.git", branch = "feat/zk-op", default-features = false, features = [
    "taiko",
    "std",
] }
revm-primitives = { git = "https://github.com/taikoxyz/revm.git", branch = "feat/zk-op", default-features = false, features = [
    "taiko",
    "std",
] }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.0" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risczero.0" }
harness-core = { path = "../../../harness/core" }
harness = { path = "../../../harness/macro", features = ["risc0"]}

[patch.crates-io]
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risczero.0" }
# crypto-bigint v0.5.5
# └── elliptic-curve v0.13.8
#     ├── ecdsa v0.16.9
#     │   └── k256 v0.13.3
#     │       ├── ethers-core v2.0.14
#     │       │   └── ethers-contract v2.0.14
#     │       │       [dev-dependencies]
#     │       │       └── revm v7.2.0 (/home/ubuntu/revm/crates/revm)
#     │       └── revm-precompile v5.1.0 (/home/ubuntu/revm/crates/precompile)
#     │           └── revm v7.2.0 (/home/ubuntu/revm/crates/revm)
#     ├── ethers-core v2.0.14 (*)
#     └── k256 v0.13.3 (*)


