[package]
name = "risc0-driver"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmark"
path = "src/benchmark.rs"
harness = true

[dependencies]
raiko-lib = { workspace = true, optional = true }

risc0-zkvm = { workspace = true, optional = true }
bonsai-sdk = { workspace = true, optional = true }

alloy-primitives = { workspace = true, optional = true }
alloy-sol-types = { workspace = true, optional = true }

ethers-contract = { workspace = true, optional = true }
ethers-core = { workspace = true, optional = true }
ethers-providers = { workspace = true, optional = true }

tracing = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }

cfg-if = { workspace = true, optional = true }
log = { workspace = true, optional = true }
bincode = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
typetag = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
lazy_static = { workspace = true, optional = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
thiserror = { workspace = true }

[features]
enable = [
    "raiko-lib",
    "risc0-zkvm",
    "bonsai-sdk",
    "alloy-primitives",
    "alloy-sol-types",
    "ethers-contract",
    "ethers-core",
    "ethers-providers",
    "tracing",
    "serde",
    "once_cell",
    "anyhow",
    "cfg-if",
    "log",
    "bincode",
    "bytemuck",
    "typetag",
    "serde_with",
    "serde_json",
    "hex",
    "reqwest",
    "lazy_static",
]
cuda = ["risc0-zkvm?/cuda"]
metal = ["risc0-zkvm?/metal"]
bench = []

[dev-dependencies]
env_logger = { workspace = true }
