name: CI - All

on:
  push:
    branches: ["main"]
    paths:
      - "host/**"
      - "lib/**"
      - "script/**"
  pull_request:
    paths:
      - "host/**"
      - "lib/**"
      - "script/**"
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test-native:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/ci-native.yml

  build-test-risc0:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/ci-risc0.yml

  build-test-sp1:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/ci-sp1.yml

  build-test-sgx-all:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/ci-sgx-all.yml

  test-lib:
    name: Test raiko-lib
    runs-on: [taiko-runner]
    if: github.event.pull_request.draft == false
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - run: cargo test -p raiko-lib --features=std
