name: CI Integration test - Reusable

on:
  workflow_call:
    inputs:
      version_name:
        type: string
        required: true
      version_toolchain:
        type: string
        required: true


env:
  CI: 1
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-run-integration:
    if: ${{ github.event.pull_request.draft == false }}
    name: Build and run integration
    runs-on: [taiko-runner]
    timeout-minutes: 120

    env:
      TARGET: ${{ inputs.version_name }}
      CI: 1
      MOCK: 1

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.version_toolchain }}
          profile: minimal

      - name: Setup sccache
        if: ${{ inputs.version_name }} == risc0
        uses: risc0/risc0/.github/actions/sccache@release-0.19

      - name: Install ${{ inputs.version_name }}
        run: make install

      - name: Build ${{ inputs.version_name }} prover
        run: make build

    #  TODO:(petar) re add to CI after fixing sgx directory setup
    #
    #   - name: Run integration test for ${{ inputs.version_name }} prover
    #     run: make integration
