name: CI - Lint

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  merge_group:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  clippy:
    name: clippy
    runs-on: [taiko-runner]
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Run clippy check host
        run: cargo clippy -p raiko-host -p raiko-lib -p raiko-core -p harness -p raiko-tasks --all-features  -- -D warnings
      - name: Run clippy check risc0
        run: |
          cargo clippy -p risc0-builder --all-features -- -D warnings
          cargo clippy -p risc0-driver --features enable -- -D warnings
          # cd ./provers/risc0/guest
          # cargo clippy --all-features -- -D warnings
      - name: Run clippy check sp1
        run: |
          cargo clippy -p sp1-builder --all-features -- -D warnings
          cargo clippy -p sp1-driver --features enable -- -D warnings
      - name: Run clippy check sgx
        run: |
          cargo clippy -p sgx-guest -p sgx-prover -p raiko-setup --all-features -- -D warnings

  fmt:
    name: fmt
    runs-on: [taiko-runner]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Run format script for all targets
        run: cargo fmt --all --check
