name: CI - Native

on: workflow_call

jobs:
  build-test-native:
    name: Build and test native
    uses: ./.github/workflows/ci-build-test-reusable.yml
    with:
      version_name: "native"
      version_toolchain: "nightly-2024-04-17"
