name: CI - Native

on: 
  workflow_call:
  pull_request:
    paths:
      - "core/**"
      - "host/**"
      - "lib/**"
      - "!doc/**"
      - "script/**"
      - "taskdb/**"

jobs:
  set-taskdb:
    runs-on: ubuntu-latest
    outputs:
      taskdb: ${{ steps.check_file.outputs.taskdb }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Check if specific file changed
        id: check_file
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          if git diff --name-only origin/$BASE_BRANCH ${{ github.sha }} | grep -q "taskdb/src/redis_db.rs"; then
            echo "redis changed"
            echo "::set-output name=taskdb::raiko-tasks/redis-db"
          else
            echo "redis unchanged"
            echo "::set-output name=taskdb::"
          fi

  build-test-native:
    name: Build and test native
    needs: set-taskdb
    uses: ./.github/workflows/ci-build-test-reusable.yml
    with:
      version_name: "native"
      version_toolchain: "nightly-2024-09-05"
      taskdb: ${{ needs.set-taskdb.outputs.taskdb }}

  integration-test-native:
    name: Run integration tests on native
    needs: set-taskdb
    uses: ./.github/workflows/ci-integration-reusable.yml
    with:
      version_name: "native"
      version_toolchain: "nightly-2024-09-05"
      taskdb: ${{ needs.set-taskdb.outputs.taskdb }}
