name: CI - SGX Docker

on:
  workflow_call:
  push:
    branches: ["main"]
    paths:
      - "docker/**"
      - "!docs/**"
  pull_request:
    paths:
      - "docker/**"
      - "!docs/**"

jobs:
  build-test-sgx-with-docker:
    name: Build and test sgx with Docker
    runs-on: [taiko-runner]
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - name: Setup and build sgx docker
        run: |
          cd docker
          docker compose build raiko --no-cache
        shell: bash
