name: CI - SP1

on:
  workflow_call:
  push:
    branches: ["main"]
    paths:
      - "provers/sp1/**"
  pull_request:
    paths:
      - "provers/sp1/**"
  merge_group:

jobs:
  build-test-sp1:
    name: Build and test sp1
    uses: ./.github/workflows/ci-build-test-reusable.yml
    with:
      version_name: "sp1"
      version_toolchain: "nightly-2024-04-18"

  integration-test-native:
    name: Build and run integration tests on sp1
    uses: ./.github/workflows/ci-integration-reusable.yml
    with:
      version_name: "sp1"
      version_toolchain: "nightly-2024-04-17"
